# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d53a176a45ec687861da4b299a9a9d3e77107ad7050314736df2e42930ae91fd9cc02c560963af6127c643fcd0dcd9b5a8aa04ae0287c36a4ddb9ef02055010

test:
  secret_key_base: 47c1a737191eb105a0e47cd3689654b010f1de4c83acc5af4e8b98878a54f26c93d85ddaee128ce0d477c43d8d16701b80bb9b72ce85fb184df98550ce000e5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
